### ISSUE TITLE
template for bit boolean doesn't work.

### ISSUE THREAD

**Issue by RavenKyu** [RavenKyu/restful-modbus-api#12]
template -
```yaml
templates:
    template_for_scheduling:
      code: |
        def main():
            try:
                data = read_coils('-a 0 -c 256 -i 1')
                print(data)
            finally:
                client.close()
            return data

      template:
        - key: CH01-ID01-ENABLE
          note: ''
          type: BIT1_BOOLEAN
          scale: 1
        - key: CH01-ID01-F_DOOR
          note: ''
          type: BIT1_BOOLEAN
          scale: 1
```

result -
```json
{
    "data": {
        "CH01-ID01-ALARM": {
            "hex": "11",
            "note": "",
            "scale": 1,
            "scaled_value": 1,
            "type": "BIT1_BOOLEAN",
            "value": true
        },
        "CH01-ID01-ENABLE": {
            "hex": "15",
            "note": "",
            "scale": 1,
            "scaled_value": 1,
            "type": "BIT1_BOOLEAN",
            "value": true
        }
}
