### ISSUE TITLE
changing the input style of cron setting

### ISSUE THREAD

**Issue by RavenKyu** [RavenKyu/restful-modbus-api#15]
current:
```yaml
trigger:
    type: cron
    setting:
      second: '*/5'  # every 3 seconds
```
